version: '3.8'

services:
  identity-service:
    build: ./src/identity-service
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/identity_db

        #  frontend:
        #    build: ./src/identity-service/frontend
        #    ports:
        #      - "5173:80"
        #    environment:
        #      - VITE_API_BASE=http://172.16.16.134:8000/api
        #    depends_on:
        #      - identity-service

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: identity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
