apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: us-central1-docker.pkg.dev/carbon-beanbag-465619-m4/soa915-project-repo/product-service
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          value: "fMC3adp-XLYg2biE1w8qFFKwxkDjr3N3t6OpvchjrNY"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP
